name: npm Tools Package

on:
  release:
    types: [created]

env: 
  packages: epubtopdf

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      package: $packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: packages/$package
      - run: npm test
        working-directory: packages/$package

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env: 
      package: $packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        working-directory: packages/$package
      - run: npm publish
        working-directory: packages/$package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
